description = "Large Language Model As A Service Providers"

[providers]

[providers.deepseek]
description = "DeepSeek"
api_key_name = "DEEPSEEK_API_KEY"
base_url = "https://api.deepseek.com"
beta_base_url = "https://api.deepseek.com/beta"
chat_model_id = "deepseek-chat"
coder_model_id = "deepseek-chat"
reasoner_model_id = "deepseek-reasoner"

[providers.aliyun_qwen]
description = "Qwen"
api_key_name = "ALIYUN_API_KEY"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
beta_base_url = "https://dashscope.aliyuncs.com/api/v2/apps/protocols/compatible-mode/v1"
chat_model_id = "qwen-plus-latest"
coder_model_id = "qwen3-coder-plus"
reasoner_model_id = "qwen3-max-2026-01-23"
embedding_model_id = "text-embedding-v3"

[providers.moonshot]
description = "Moonshot"
api_key_name = "MOONSHOT_API_KEY"
base_url = "https://api.moonshot.cn/v1"
beta_base_url = ""
chat_model_id = "kimi-k2-turbo-preview"
coder_model_id = "kimi-k2.5"
reasoner_model_id = "kimi-k2.5"
default_model_type = "reasoner"

[providers.zhipu]
description = "Zhipu"
api_key_name = "ZHIPU_API_KEY"
base_url = "https://open.bigmodel.cn/api/paas/v4/"
beta_base_url = ""
chat_model_id = "glm-4.7"
coder_model_id = "glm-4.7"
reasoner_model_id = "glm-4.7"

[providers.openai]
description = "OpenAI"
api_key_name = "OPENAI_API_KEY"
base_url = "https://api.openai.com/v1"
beta_base_url = ""
chat_model_id = "gpt-5.2"
coder_model_id = "gpt-5.2-codex"
reasoner_model_id = "gpt-5.2"

[providers.openrouter]
description = "OpenRouter"
api_key_name = "OPENROUTER_API_KEY"
base_url = "https://openrouter.ai/api/v1"
beta_base_url = ""
chat_model_id = "google/gemini-3-flash-preview"
coder_model_id = "google/gemini-3-flash-preview"
reasoner_model_id = "google/gemini-3-pro-preview"

[providers.local]
description = "Local"
api_key_name = "LOCAL_API_KEY"
base_url = "http://localhost:5810/v1"
beta_base_url = ""
chat_model_id = "qwen3"
coder_model_id = ""
reasoner_model_id = "qwen3-thinking"
embedding_model_id = "snowflake"

[providers.lmstudio]
description = "LM Studio"
api_key_name = "LM_STUDIO_API_KEY"
base_url = "http://127.0.0.1:1234/v1"
beta_base_url = ""
chat_model_id = "qwen3-30b-a3b-instruct-2507"
coder_model_id = ""
reasoner_model_id = "qwen3-30b-a3b-thinking-2507"

[defaults]
provider = "aliyun_qwen"
model_type = "chat"

[aliases]
qwen = "aliyun_qwen"
